appname: demo
database:
  driver: postgres
  source: host=127.0.0.1 port=5432 user=postgres dbname=example sslmode=disable password=MTI3LjAuMC4x
demoapp:
  name: cmd-demo
  enablehttp: true
  httpport: 9000
  enablegrpc: true
  grpcport: 8000
  host: example.com
